// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1773239925);
user_pref("app.update.lastUpdateTime.background-update-timer", 1773239925);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1773239925);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1757074558);
user_pref("browser.laterrun.bookkeeping.sessionCount", 24);
user_pref("browser.startup.homepage_override.buildID", "20240801134912");
user_pref("browser.startup.homepage_override.mstone", "115.14.0");
user_pref("browser.theme.toolbar-theme", 0);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.lastAppBuildId", "20251120211745");
user_pref("extensions.lastAppVersion", "7.0.30");
user_pref("extensions.lastPlatformVersion", "115.14.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.zotero.autoRenameFiles.linked", true);
user_pref("extensions.zotero.automaticTags", false);
user_pref("extensions.zotero.dataDir", "/home/marius/Zotero");
user_pref("extensions.zotero.export.bibliographySettings", "{\"mode\":\"bibliography\",\"method\":\"copy-to-clipboard\"}");
user_pref("extensions.zotero.export.lastLocale", "en-US");
user_pref("extensions.zotero.export.lastStyle", "http://www.zotero.org/styles/bibtex");
user_pref("extensions.zotero.export.lastTranslator", "9cb70025-a888-4a29-a210-93ec52da40d4");
user_pref("extensions.zotero.export.translatorSettings", "{\"exportCharset\":\"UTF-8\",\"exportNotes\":false,\"exportFileData\":true,\"useJournalAbbreviation\":false,\"includeAnnotations\":false}");
user_pref("extensions.zotero.firstRun.skipFirefoxProfileAccessCheck", true);
user_pref("extensions.zotero.firstRun2", false);
user_pref("extensions.zotero.ignoreLegacyDataDir.auto", true);
user_pref("extensions.zotero.lastCreatorFieldMode", 1);
user_pref("extensions.zotero.lastSelectedPrefPane", "zotero-prefpane-cite");
user_pref("extensions.zotero.lastViewedFolder", "C2");
user_pref("extensions.zotero.newItemTypeMRU", "conferencePaper,book,blogPost,newspaperArticle,journalArticle");
user_pref("extensions.zotero.pane.persist", "{\"zotero-reader-sidebar-pane\":{\"collapsed\":\"false\",\"width\":\"240\"},\"zotero-layout-switcher\":{\"orient\":\"horizontal\"},\"zotero-items-splitter\":{\"orient\":\"horizontal\"},\"zotero-item-pane\":{\"width\":\"337\",\"height\":\"205\"},\"zotero-context-splitter\":{\"state\":\"\"},\"zotero-context-splitter-stacked\":{\"state\":\"open\"}}");
user_pref("extensions.zotero.panes.abstract.open", false);
user_pref("extensions.zotero.panes.attachment-annotations.open", true);
user_pref("extensions.zotero.panes.attachment-info.open", true);
user_pref("extensions.zotero.panes.attachments.open", false);
user_pref("extensions.zotero.panes.context-all-notes.open", true);
user_pref("extensions.zotero.panes.context-item-notes.open", true);
user_pref("extensions.zotero.panes.info.open", true);
user_pref("extensions.zotero.panes.libraries-collections.open", true);
user_pref("extensions.zotero.panes.notes.open", true);
user_pref("extensions.zotero.panes.related.open", true);
user_pref("extensions.zotero.panes.tags.open", true);
user_pref("extensions.zotero.prefVersion", 13);
user_pref("extensions.zotero.reader.contentDarkMode", false);
user_pref("extensions.zotero.sourceList.persist", "{\"L1\":true,\"C1\":true,\"P1\":false,\"C6\":true}");
user_pref("extensions.zotero.sync.reminder.setUp.enabled", false);
user_pref("extensions.zotero.sync.reminder.setUp.lastDisplayed", 1757075031);
user_pref("extensions.zotero.useDataDir", true);
user_pref("extensions.zoteroOpenOfficeIntegration.lastAttemptedVersion", "7.0.5.SOURCE");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1773239978);
user_pref("intl.accept_languages", "en-US, en");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.hashValue", "94531e267314de661b2205c606283fb066d781e5c11027578f2a3c3aa353437c2289544074a28101b6b6f0179f0fe6bd890a0ae2bb6e1cf9053650472576366c");
user_pref("media.gmp-gmpopenh264.lastDownload", 1768210303);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1768210302);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1768210303);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.2");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1773239978648");
user_pref("security.sandbox.content.tempDirSuffix", "99ff36fa-73be-471b-9d0c-0657b9db3be5");
user_pref("storage.vacuum.last.content-prefs.sqlite", 1771945817);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1772729402);
