[defaults]
format = "{time}\n"
autostart = false
paused_state_text = "paused"
resumed_state_text = "resumed"

[[sessions]]
id = "work"
name = "Work"
duration = "25m"
time_format = "%M:%S"
command = "~/.config/uair/blink-notify.sh 'Work Done!' 'Time for a break'"

[[sessions]]
id = "rest"
name = "Rest"
duration = "5m"
time_format = "%M:%S"
command = "~/.config/uair/blink-notify.sh 'Rest Done!' 'Back to work' & uair"
